CFLAGS=-Wall

all:
	gcc -o CIELAB CIELAB.c $(CFLAGS)
	gcc -o CLEANUP CLEANUP.c $(CFLAGS)
	gcc -o HORSES HORSES.c $(CFLAGS)
	gcc -o JOHNY JOHNY.c $(CFLAGS)

clean:
	rm -rf CIELAB CLEANUP HORSES JOHNY a.out     \

