CFLAGS=-Wall

all:
	gcc -o Life-the-Universe-Everything Life-the-Universe-Everything.c $(CFLAGS)
	gcc -o ATM ATM.c $(CFLAGS)
	gcc -o Enormous-Input-Test Enormous-Input-Test.c $(CFLAGS)
	gcc -o Factorial Factorial.c $(CFLAGS)
	gcc -o Small-Factorial Small-Factorial.c $(CFLAGS)
	gcc -o Tsort Tsort.c $(CFLAGS)
	gcc -o TLG TLG.c $(CFLAGS)
	gcc -o MUFFINS3 MUFFINS3.c $(CFLAGS)
	gcc -o SUMTRIAN SUMTRIAN.c $(CFLAGS)
	gcc -o PERMUT2 PERMUT2.c $(CFLAGS)
	gcc -o CIELRCPT CIELRCPT.c $(CFLAGS) -lm
	gcc -o ONP ONP.c $(CFLAGS)
	gcc -o FLOW001 FLOW001.c $(CFLAS)
	gcc -o RECIPE RECIPE.c $(CFLAS)
	gcc -o SNAPE SNAPE.c $(CFLAGS) -lm
	gcc -o FLOW006 FLOW006.c $(CFLAGS)
	gcc -o REMISS REMISS.c $(CFLAGS)
	gcc -o FLOW002 FLOW002.c $(CFLAGS)
	gcc -o LUCKFOUR LUCKFOUR.c $(CFLAGS)
	gcc -o START01 START01.c $(CFLAGS)
	gcc -o FLOW004 FLOW004.c $(CFLAGS)
	gcc -o COMM3 COMM3.c $(CFLAGS)
	gcc -o FSQRT FSQRT.c $(CFLAGS) -lm
	gcc -o FLOW018 FLOW018.c $(CFLAGS)
	gcc -o FLOW008 FLOW008.c $(CFLAGS)
	gcc -o FLOW005 FLOW005.c $(CFLAGS)
	gcc -o HEADBOB HEADBOB.c $(CFLAGS)
	gcc -o FLOW013 FLOW013.c $(CFLAGS)
	gcc -o PRB01 PRB01.c $(CFLAGS)
	gcc -o PALL01 PALL01.c $(CFLAGS)
	gcc -o GDOG GDOG.c $(CFLAGS)
	gcc -o FLOW009 FLOW009.c $(CFLAGS)

clean:
	rm -rf Life-the-Universe-Everything ATM 	\
	Enormous-Input-Test Factorial Small-Factorial	\
	Tsort TLG MUFFINS3 SUMTRIAN PERMUT2 CIELRCPT	\
	ONP FLOW001 RECIPE SNAPE FLOW006 REMISS FLOW002	\
	LUCKFOUR START01 FLOW004 COMM3 FSQRT FLOW018 	\
	FLOW008 FLOW005 HEADBOB FLOW013 PRB01 PALL01	\
	GDOG FLOW009 a.out
