CFLAGS=-Wall

all:
	gcc -o Life-the-Universe-Everything Life-the-Universe-Everything.c $(CFLAGS)
	gcc -o ATM ATM.c $(CFLAGS)
	gcc -o Enormous-Input-Test Enormous-Input-Test.c $(CFLAGS)
	gcc -o Factorial Factorial.c $(CFLAGS)
	gcc -o Small-Factorial Small-Factorial.c $(CFLAGS)
	gcc -o Tsort Tsort.c $(CFLAGS)
	gcc -o TLG TLG.c $(CFLAGS)
	gcc -o MUFFINS3 MUFFINS3.c $(CFLAGS)

clean:
	rm -rf Life-the-Universe-Everything ATM 	\
	Enormous-Input-Test Factorial Small-Factorial	\
	Tsort TLG MUFFINS3 a.out
