CFLAGS=-Wall

all:
	gcc -o Life-the-Universe-Everything Life-the-Universe-Everything.c $(CFLAGS)
	gcc -o ATM ATM.c $(CFLAGS)
	gcc -o Enormous-Input-Test Enormous-Input-Test.c $(CFLAGS)
	gcc -o Factorial Factorial.c $(CFLAGS)
	gcc -o Small-Factorial Small-Factorial.c $(CFLAGS)
	gcc -o Tsort Tsort.c $(CFLAGS)
	gcc -o TLG TLG.c $(CFLAGS)
	gcc -o MUFFINS3 MUFFINS3.c $(CFLAGS)
	gcc -o SUMTRIAN SUMTRIAN.c $(CFLAGS)
	gcc -o PERMUT2 PERMUT2.c $(CFLAGS)
	gcc -o CIELRCPT CIELRCPT.c $(CFLAGS) -lm
	gcc -o ONP ONP.c $(CFLAGS)
	gcc -o FLOW001 FLOW001.c $(CFLAS)
	gcc -o RECIPE RECIPE.c $(CFLAS)
	gcc -o SNAPE SNAPE.c $(CFLAGS) -lm 
	gcc -o FLOW006 FLOW006.c $(CFLAGS) 

clean:
	rm -rf Life-the-Universe-Everything ATM 	\
	Enormous-Input-Test Factorial Small-Factorial	\
	Tsort TLG MUFFINS3 SUMTRIAN PERMUT2 CIELRCPT	\
	ONP FLOW001 RECIPE SNAPE FLOW006 a.out
